### ISSUE TITLE
Why data from users cannot store in database

### ISSUE THREAD

**Issue by sidaurukfreddy** [shivraj-chari/codeigniter-facebook-sdk-v4-login-library#2]
Hi thanks man for making this, my quick question is why the data cannot store in database in other hand you provide folder database, what do i wrong here please guide me ?

Thanks

**Comment by shivraj-chari** [comment]
Well you can save the data in database  and  that's why the database schema is provided.The demo of the library doesn't  include storing user data in database, it stores data in session.You can modify the code depending upon your requirement.
